services:
    ubuntu:
        image: gustavovinicius/ubuntu_awscli:v2
        ports:
            - 80:80
            - 81:81
        volumes:
            - ./:/home/gustavo
        container_name: aws
        networks:
            ng-app-network:
                ipv4_address: 10.0.0.2

networks:
    ng-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"