services:
    api:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 80:80
        volumes:
            - ./api:/var/www/html/api
        container_name: api
        # depends_on:
        #     - mysql
        #     - mailhog_yii
        networks:
            stddocker-app-network:
                ipv4_address: 11.0.0.4

    my_rabbitmq:
        image: rabbitmq:3.9-management
        container_name: my_rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            stddocker-app-network:
                ipv4_address: 11.0.0.3

networks:
    stddocker-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "11.0.0.0/16"