version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    ports:
      - "9090:9090"

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: service1
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    ports:
      - "9091:9091"

  nginx:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge