version: '3'

services:
    webserver:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        volumes:
            - ./webserver:/var/www/html
        ports:
            - 80:80
        container_name: webserver
        network_mode: "host"
