services:
    aws:
        build:
            context: .
            dockerfile: aws.dockerfile
        ports:
            - 80:80
            - 81:81
        volumes:
            - ./:/home/gustavo
        container_name: aws
        networks:
            ng-app-network:
                ipv4_address: 10.0.0.2
    
    server:
        build:
            context: .
            dockerfile: localubuntu.dockerfile
        ports:
            - 83:80
        volumes:
            - ./:/home/gustavo
        container_name: server
        networks:
            ng-app-network:
                ipv4_address: 10.0.0.3

networks:
    ng-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"